# docker-compose up -d
version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis_test
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb
    ports:
      - '6378:6379'
    volumes:
      - './redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
